const SET_STATE = 'SET_STATE';
const CHECK_COUNTRY = 'CHECK_COUNTRY';
const SET_SEARCH_COUNTRY = 'SET_SEARCH_COUNTRY';
const RESET_SEARCH_COUNTRY = 'RESET_SEARCH_COUNTRY';


const CHECK_TYPE = 'CHECK_TYPE';

const CHECK_RATING = 'CHECK_RATING';

const SET_REVIEWS = 'SET_REVIEWS';

const RESET_FILTER = 'RESET_FILTER';

const SET_PRICE_RANGE = 'SET_PRICE_RANGE';

const SET_FILTERED_CARDS = 'SET_FILTERED_CARDS';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export {
    SET_STATE,
    CHECK_COUNTRY,
    SET_SEARCH_COUNTRY,
    RESET_SEARCH_COUNTRY,
    CHECK_TYPE,
    CHECK_RATING,
    SET_REVIEWS,
    RESET_FILTER,
    SET_PRICE_RANGE,
    SET_FILTERED_CARDS,
    SET_CURRENT_PAGE,
}
